name: Comment on the pull request
on:
  workflow_run:
    workflows:
      - ScreenShotTest
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifact
        run: echo "download artifact later"
      - name: Comment PR
        if: ${{ hashFiles('preview-screenshots/out/failures/*.png') != '' }}
        continue-on-error: true # https://github.com/DroidKaigi/conference-app-2022/issues/497
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            There are differences in Compose previews. Please check your build and download the diff artifact.
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
